# -*- coding: utf-8 -*-
"""
Part Glossary generator for GitPDM.

Scans previews/**/*.json manifests (already produced by the exporter) and
maintains a "Part Glossary" section in the repository's README.md so parts
are visible without digging through folders.
"""

import json
import re
from fnmatch import fnmatch
from pathlib import Path
from typing import Any, Dict, List, Optional

from freecad_gitpdm.core import log

START_MARKER = "<!-- GITPDM:PART-GLOSSARY:START -->"
END_MARKER = "<!-- GITPDM:PART-GLOSSARY:END -->"

# Object type prefixes/names that indicate an assembly rather than a single part.
_ASSEMBLY_TYPE_PREFIXES = ("Assembly::", "App::Link")


def detect_category(doc) -> str:
    """
    Best-effort heuristic: "assembly" if the document links to other parts
    or contains multiple solid bodies, otherwise "part".
    """
    try:
        bodies = 0
        for obj in doc.Objects:
            type_id = getattr(obj, "TypeId", "") or ""
            if any(type_id.startswith(p) for p in _ASSEMBLY_TYPE_PREFIXES):
                return "assembly"
            if type_id == "PartDesign::Body":
                bodies += 1
        if bodies > 1:
            return "assembly"
    except Exception as e:
        log.debug(f"Category detection failed: {e}")
    return "part"


def _excluded(source_rel: str, patterns: List[str]) -> bool:
    return any(fnmatch(source_rel, pat) for pat in patterns)


def _load_entry(json_path: Path, repo_root: Path) -> Optional[Dict[str, Any]]:
    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
    except Exception as e:
        log.debug(f"Skipping unreadable manifest {json_path}: {e}")
        return None

    source_rel = data.get("source", {}).get("path")
    if not source_rel:
        return None

    png_path = json_path.with_suffix(".png")
    artifacts = data.get("artifacts", {}) or {}
    model_rel = artifacts.get("model") or artifacts.get("stl")

    bbox = (data.get("stats", {}) or {}).get("bboxMm")
    if isinstance(bbox, list) and len(bbox) == 3 and all(v is not None for v in bbox):
        bbox_str = f"{bbox[0]} x {bbox[1]} x {bbox[2]}"
    else:
        bbox_str = "-"

    return {
        "name": Path(source_rel).stem,
        "source_rel": source_rel,
        "category": data.get("category", "part"),
        "png_rel": png_path.relative_to(repo_root).as_posix()
        if png_path.is_file()
        else None,
        "model_rel": model_rel,
        "bbox": bbox_str,
    }


def collect_entries(
    repo_root: Path, glossary_cfg: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """Scan previews/ for manifests and apply onlyAssemblies/exclude filters."""
    previews_dir = repo_root / "previews"
    if not previews_dir.is_dir():
        return []

    only_assemblies = bool(glossary_cfg.get("onlyAssemblies", False))
    exclude_patterns = [
        p for p in glossary_cfg.get("exclude", []) if isinstance(p, str)
    ]

    entries = []
    for json_path in sorted(previews_dir.rglob("*.json")):
        entry = _load_entry(json_path, repo_root)
        if not entry:
            continue
        if _excluded(entry["source_rel"], exclude_patterns):
            continue
        if only_assemblies and entry["category"] != "assembly":
            continue
        entries.append(entry)

    entries.sort(key=lambda e: e["source_rel"])
    return entries


def render_section(entries: List[Dict[str, Any]]) -> str:
    """Render the fenced Part Glossary markdown section."""
    lines = [
        START_MARKER,
        "## Part Glossary",
        "",
        "_Auto-generated by GitPDM from exported previews. Do not edit this "
        "section by hand; it is regenerated on export._",
        "",
    ]
    if not entries:
        lines.append("_No parts exported yet._")
    else:
        lines.append("| Preview | Name | Path | Category | Bounding Box (mm) |")
        lines.append("|---|---|---|---|---|")
        for e in entries:
            thumb = f"![{e['name']}]({e['png_rel']})" if e["png_rel"] else ""
            name = f"[{e['name']}]({e['model_rel']})" if e["model_rel"] else e["name"]
            lines.append(
                f"| {thumb} | {name} | `{e['source_rel']}` | {e['category']} | {e['bbox']} |"
            )
    lines.append(END_MARKER)
    return "\n".join(lines)


def update_readme(repo_root: Path, section_md: str) -> Path:
    """
    Insert or replace the Part Glossary section in the repo's README.md.
    Creates README.md if it does not already exist (any casing).
    """
    readme_path = None
    for candidate in repo_root.glob("[Rr][Ee][Aa][Dd][Mm][Ee].[Mm][Dd]"):
        readme_path = candidate
        break
    if readme_path is None:
        readme_path = repo_root / "README.md"

    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )

    if readme_path.is_file():
        original = readme_path.read_text(encoding="utf-8")
    else:
        original = ""

    if pattern.search(original):
        updated = pattern.sub(section_md, original)
    elif original.strip():
        updated = original.rstrip() + "\n\n" + section_md + "\n"
    else:
        updated = f"# {repo_root.name}\n\n{section_md}\n"

    readme_path.write_text(updated, encoding="utf-8", newline="\n")
    return readme_path


def regenerate(repo_root: Path, preset: Dict[str, Any]) -> Optional[Path]:
    """
    Rescan previews/ and rewrite the Part Glossary section in README.md.
    Returns the README path if updated, or None if the feature is disabled.
    """
    glossary_cfg = preset.get("partGlossary", {}) or {}
    if not glossary_cfg.get("enabled", True):
        return None

    entries = collect_entries(repo_root, glossary_cfg)
    section_md = render_section(entries)
    try:
        return update_readme(repo_root, section_md)
    except Exception as e:
        log.warning(f"Failed to update README part glossary: {e}")
        return None
